---
- hosts: all
  become: yes
  vars:
    update_vm: yes
  tasks:
    - name: Update VM
      ansible.builtin.include_role:
        name: ewc-ansible-role-update-system
      when: update_vm

    - name: Jupyterhub
      ansible.builtin.include_role:
        name: ewc-ansible-role-jupyterhub-local