---
- name: Jupyterhub Flavour
  hosts: all
  become: true
  vars:
    update_vm: true
  tasks:
    - name: Update VM
      ansible.builtin.include_role:
        name: ewc-ansible-role-update-system
      when: update_vm

    - name: Jupyterhub
      ansible.builtin.include_role:
        name: ewc-ansible-role-jupyterhub-local
