---
# ⚠️ DEPRECATION WARNING:
# This playbook is deprecated and will be removed in release 2.0.0.
# Please use instead `https://github.com/ewcloud/ewc-flavours/blob/main/playbooks/jupyterhub-flavour/jupyterhub-flavour.yml`.
# Contact the EWC support for migration assistance.

- hosts: all
  become: yes
  vars:
    update_vm: yes
  tasks:
    - name: Display deprecation warning
      ansible.builtin.debug:
        msg: |
          ⚠️ DEPRECATION WARNING:
          This playbook is deprecated and will be removed in release 2.0.0.
          Please use instead `https://github.com/ewcloud/ewc-flavours/blob/main/playbooks/jupyterhub-flavour/jupyterhub-flavour.yml`.
          Contact the EWC support for migration assistance.

    - name: Update VM
      ansible.builtin.include_role:
        name: ewc-ansible-role-update-system
      when: update_vm

    - name: Jupyterhub
      ansible.builtin.include_role:
        name: ewc-ansible-role-jupyterhub-local