---
roles:
  - name: ewc-ansible-role-update-system-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-update-system.git
    version: 1.0.0

  - name: ewc-ansible-role-mars-client-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-mars-client.git
    version: 1.0.1

  - name: ewc-ansible-role-conda-1.1
    src: https://github.com/ewcloud/ewc-ansible-role-conda.git
    version: 1.1.0

  - name: ewc-ansible-role-ecmwf-toolbox-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-ecmwf-toolbox.git
    version: 1.0.1

  - name: ewc-ansible-role-jupyterhub-local-1.0
    src: https://github.com/ewcloud/ewc-ansible-role-jupyterhub-local.git
    version: 1.0.1
